version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - "9411:9411"
    networks:
      - erudio-network

  naming-server:
    image: library/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - erudio-network

  api-gateway:
    image: library/api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    environment:
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - erudio-network

networks:
  erudio-network:
    driver: bridge